const DYNAMIC_PATTERNS: readonly RegExp[] = [
  /^:[rR][0-9a-zA-Z]*:$/,
  /^react[-_]/i,
  /^ember[-_]?\d/i,
  /^ng-c\d/i,
  /^vue[-_]/i,
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i,
  /^\d+$/,
  /^(?:css|sc)-[0-9a-z]+$/i,
  /^.+-\d{6,}$/,
];

/** Detect whether an element ID appears to be dynamically generated by a framework. */
export function isDynamicId(id: string): boolean {
  if (id.length === 0) return false;
  return DYNAMIC_PATTERNS.some((pattern) => pattern.test(id));
}
